#include "../../util/encoding.h"

enum __vmcs_fields_control_e
{

    // 16 bit control fieldls
    CTRL_VPID = VMCS_ENCODE_COMPONENT_FULL_16(control, 0),
    CTRL_PINV = VMCS_ENCODE_COMPONENT_FULL_16(control, 1),
    CTRL_EPTP_IDX = VMCS_ENCODE_COMPONENT_FULL_16(control, 2),
    CTRL_HLAT_PREFIX_SIZE = VMCS_ENCODE_COMPONENT_FULL_16(control, 3),
    CTRL_LAST_PID_POINTER_INDEX = VMCS_ENCODE_COMPONENT_FULL_16(control, 4),
   

    // 32 bit control fields 
    
    CTRL_PIN_BASED_VM_EXECUTION_CONTROLS = VMCS_ENCODE_COMPONENT_FULL_32(control, 0),
    CTRL_PRIMARY_PROCESSOR_BASED_VM_EXECUTION_CONTROLS = VMCS_ENCODE_COMPONENT_FULL_32(control, 1),
    CTRL_EXCEPTION_BITMAP = VMCS_ENCODE_COMPONENT_FULL_32(control, 2),
    CTRL_PAGE_FAULT_ERROR_CODE_MASK = VMCS_ENCODE_COMPONENT_FULL_32(control, 3),
    CTRL_PAGE_FAULT_ERROR_CODE_MATCH = VMCS_ENCODE_COMPONENT_FULL_32(control, 4),
    CTRL_CR3_TARGET_COUNT = VMCS_ENCODE_COMPONENT_FULL_32(control, 5), 
    CTRL_PRIMARY_VM_EXIT_CONTROLS = VMCS_ENCODE_COMPONENT_FULL_32(control, 6),
    CTRL_VM_EXIT_MSR_STORE_COUNT = VMCS_ENCODE_COMPONENT_FULL_32(control, 7), 
    CTRL_VM_EXIT_MSR_LOAD_COUNT = VMCS_ENCODE_COMPONENT_FULL_32(control, 8),
    CTRL_VM_ENTRY_CONTROLS = VMCS_ENCODE_COMPONENT_FULL_32(control, 9), 
    CTRL_VM_ENTRY_MSR_LOAD_COUNT = VMCS_ENCODE_COMPONENT_FULL_32(control, 10), 
    CTRL_VM_ENTRY_INTERRUPT_INFORMATION_FIELD = VMCS_ENCODE_COMPONENT_FULL_32(control, 11),
    CTRL_VM_ENTRY_EXCEPTION_ERROR_CODE = VMCS_ENCODE_COMPONENT_FULL_32(control, 12), 
    CTRL_VM_ENTRY_INSTRUCTION_LENGTH = VMCS_ENCODE_COMPONENT_FULL_32(control, 13), 
    CTRL_TPR_THRESHOLD = VMCS_ENCODE_COMPONENT_FULL_32(control, 14),
    CTRL_SECONDARY_PROCESSOR_BASED_VM_EXECUTION_CONTROLS = VMCS_ENCODE_COMPONENT_FULL_32(control, 15),
    CTRL_PLE_GAP = VMCS_ENCODE_COMPONENT_FULL_32(control, 16),

    
    // 64 bit control fields

    CTRL_IO_BITMAP_ADDRESS_A = VMCS_ENCODE_COMPONENT_FULL_64(control, 0),
    CTRL_IO_BITMAP_ADDRESS_B = VMCS_ENCODE_COMPONENT_FULL_64(control, 1), 
    CTRL_MSR_BITMAP_ADDRESS = VMCS_ENCODE_COMPONENT_FULL_64(control, 2),
    CTRL_VM_EXIT_MSR_STORE_ADDRESS = VMCS_ENCODE_COMPONENT_FULL_64(control,3),
    CTRL_VM_EXIT_MSR_LOAD_ADDRESS = VMCS_ENCODE_COMPONENT_FULL_64(control, 4),
    CTRL_VM_ENTRY_MSR_LOAD_ADDRESS = VMCS_ENCODE_COMPONENT_FULL_64(control, 5),
    CTRL_EXECUTIVE_VMCS_POINTER = VMCS_ENCODE_COMPONENT_FULL_64(control, 6),
    CTRL_PML_ADDRESS = VMCS_ENCODE_COMPONENT_FULL_64(control, 7),
    CTRL_TSC_OFFSET = VMCS_ENCODE_COMPONENT_FULL_64(control, 8),
    CTRL_VIRTUAL_APIC_ADDRESS = VMCS_ENCODE_COMPONENT_FULL_64(control, 9),
    CTRL_APIC_ACCESS_ADDRESS = VMCS_ENCODE_COMPONENT_FULL_64(control, 10),
    CTRL_POSTED_INTERRUPT_DESCRIPTOR_ADDRESS = VMCS_ENCODE_COMPONENT_FULL_64(control, 11),
    CTRL_VM_FUNCTION_CONTROLLS = VMCS_ENCODE_COMPONENT_FULL_64(control, 12),
    CTRL_EPT_POINTER = VMCS_ENCODE_COMPONENT_FULL_64(control, 13),
    CTRL_EOI_EXIT_BITMAP_0 = VMCS_ENCODE_COMPONENT_FULL_64(control, 14),
    CTRL_EOI_EXIT_BITMAP_1 = VMCS_ENCODE_COMPONENT_FULL_64(control, 15),
    CTRL_EOI_EXIT_BITMAP_2 = VMCS_ENCODE_COMPONENT_FULL_64(control, 16),
    CTRL_EOI_EXIT_BITMAP_3 = VMCS_ENCODE_COMPONENT_FULL_64(control, 17),
    CTRL_EPTP_LIST_ADDRESS = VMCS_ENCODE_COMPONENT_FULL_64(control, 18),
    CTRL_VMREAD_BITMAP_ADDRESS = VMCS_ENCODE_COMPONENT_FULL_64(control, 19),
    CTRL_VMWRITE_BITMAP_ADDRESS = VMCS_ENCODE_COMPONENT_FULL_64(control, 20),
    CTRL_VIRTUALIZATION_EXCEPTION_INFO_ADDRESS = VMCS_ENCODE_COMPONENT_FULL_64(control, 21),
    CTRL_XSS_EXITING_BITMAP = VMCS_ENCODE_COMPONENT_FULL_64(control, 22),
    CTRL_ENCLS_EXITING_BITMAP = VMCS_ENCODE_COMPONENT_FULL_64(control, 23),
    CTRL_SUB_PAGE_PERMISSION_TABLE_POINTER = VMCS_ENCODE_COMPONENT_FULL_64(control, 24),
    CTRL_TSC_MULTIPLIER = VMCS_ENCODE_COMPONENT_FULL_64(control, 25),
    CTRL_TERTIARY_PROCESSOR_BASED_VM_EXECUTION_CONTROLS = VMCS_ENCODE_COMPONENT_FULL_64(control, 26),
    CTRL_ENCLV_EXITING_BITMAP = VMCS_ENCODE_COMPONENT_FULL_64(control, 27),
    CTRL_LOW_PASID_DIRECTORY_ADDRESS = VMCS_ENCODE_COMPONENT_FULL_64(control, 28),
    CTRL_HIGH_PASID_DIRECTORY_ADDRESS = VMCS_ENCODE_COMPONENT_FULL_64(control, 29),
    CTRL_SHARED_EPT_POINTER = VMCS_ENCODE_COMPONENT_FULL_64(control, 30),
    CTRL_PCONFIG_EXITING_BITMAP = VMCS_ENCODE_COMPONENT_FULL_64(control, 31),
    CTRL_HLATP = VMCS_ENCODE_COMPONENT_FULL_64(control, 32),
    CTRL_PID_POINTER_TABLE_ADDRESS = VMCS_ENCODE_COMPONENT_FULL_64(control, 33),
    CTRL_SECONDARY_VM_EXIT_CONTROLS = VMCS_ENCODE_COMPONENT_FULL_64(control, 34),
    CTRL_IA32_SPEC_CTRL_MASK = VMCS_ENCODE_COMPONENT_FULL_64(control, 35),
    CTRL_IA32_SPEC_CTRL_SHADOW = VMCS_ENCODE_COMPONENT_FULL_64(control, 36),

    //natural width control fields

    CTRL_CR0_GUEST_HOST_MASK = VMCS_ENCODE_COMPONENT_FULL(control, natural, 0),
    CTRL_CR4_GUEST_HOST_MASK = VMCS_ENCODE_COMPONENT_FULL(control, natural, 1),
    CTRL_CR0_READ_SHADOW = VMCS_ENCODE_COMPONENT_FULL(control, natural, 2),
    CTRL_CR4_READ_SHADOW = VMCS_ENCODE_COMPONENT_FULL(control, natural, 3),
    CTRL_CR3_TARGET_VALUE_0 = VMCS_ENCODE_COMPONENT_FULL(control, natural, 4),
    CTRL_CR3_TARGET_VALUE_1 = VMCS_ENCODE_COMPONENT_FULL(control, natural, 5),
    CTRL_CR3_TARGET_VALUE_2 = VMCS_ENCODE_COMPONENT_FULL(control, natural, 6),
    CTRL_CR3_TARGET_VALUE_3 = VMCS_ENCODE_COMPONENT_FULL(control, natural, 7),
};
