#include "../../util/encoding.h"

enum __vmcs_fields_vmexit_e {

	//64 bit 
	VM_EXIT_GUEST_PHYSICAL_ADDRESS = VMCS_ENCODE_COMPONENT_FULL_64(vmexit, 0),

	//32 bit

	VM_EXIT_VM_INSTRUCTION_ERROR = VMCS_ENCODE_COMPONENT_FULL_32(vmexit, 0),
	VM_EXIT_REASON = VMCS_ENCODE_COMPONENT_FULL_32(vmexit, 1),
	VM_EXIT_INTERRUPTION_INFORMATION = VMCS_ENCODE_COMPONENT_FULL_32(vmexit,2),
	VM_EXIT_INTERRUPTION_ERROR_CODE = VMCS_ENCODE_COMPONENT_FULL_32(vmexit, 3),
	VM_EXIT_IDT_VECTORING_INFORMATION_FIELD = VMCS_ENCODE_COMPONENT_FULL_32(vmexit, 4), 
	VM_EXIT_IDT_VECTORING_ERROR_CODE = VMCS_ENCODE_COMPONENT_FULL_32(vmexit, 5),
	VM_EXIT_INSTRUCTION_LENGTH = VMCS_ENCODE_COMPONENT_FULL_32(vmexit, 6), 
	VM_EXIT_INSTRUCTION_INFORMATION = VMCS_ENCODE_COMPONENT_FULL_32(vmexit, 7),

	// natural

	VM_EXIT_EXIT_QUALIFICATION = VMCS_ENCODE_COMPONENT_FULL(vmexit, natural, 0),
	VM_EXIT_IO_RCX = VMCS_ENCODE_COMPONENT_FULL(vmexit, natural, 1),
	VM_EXIT_IO_RSI = VMCS_ENCODE_COMPONENT_FULL(vmexit, natural, 2), 
	VM_EXIT_IO_RDI = VMCS_ENCODE_COMPONENT_FULL(vmexit, natural, 3), 
	VM_EXIT_IO_RIP = VMCS_ENCODE_COMPONENT_FULL(vmexit, natural, 4), 
	VM_EXIT_GUEST_LINEAR_ADDRESS = VMCS_ENCODE_COMPONENT_FULL(vmexit, natural,5),

};